version: "2"
run:
  go: "1.23"
  tests: false
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forcetypeassert
    - funlen
    - godot
    - godox
    - gosec
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - perfsprint
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
