// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/proto/cluster.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterEvent int32

const (
	ClusterEvent_ERROR         ClusterEvent = 0
	ClusterEvent_SPAWN         ClusterEvent = 1
	ClusterEvent_STOP          ClusterEvent = 2
	ClusterEvent_BEACON_ATTEST ClusterEvent = 3
	ClusterEvent_POLICY_QUERY  ClusterEvent = 4
	ClusterEvent_PROOF_VERIFY  ClusterEvent = 5
)

// Enum value maps for ClusterEvent.
var (
	ClusterEvent_name = map[int32]string{
		0: "ERROR",
		1: "SPAWN",
		2: "STOP",
		3: "BEACON_ATTEST",
		4: "POLICY_QUERY",
		5: "PROOF_VERIFY",
	}
	ClusterEvent_value = map[string]int32{
		"ERROR":         0,
		"SPAWN":         1,
		"STOP":          2,
		"BEACON_ATTEST": 3,
		"POLICY_QUERY":  4,
		"PROOF_VERIFY":  5,
	}
)

func (x ClusterEvent) Enum() *ClusterEvent {
	p := new(ClusterEvent)
	*p = x
	return p
}

func (x ClusterEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_cluster_proto_enumTypes[0].Descriptor()
}

func (ClusterEvent) Type() protoreflect.EnumType {
	return &file_pkg_proto_cluster_proto_enumTypes[0]
}

func (x ClusterEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterEvent.Descriptor instead.
func (ClusterEvent) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{0}
}

type ClusterMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Event          ClusterEvent           `protobuf:"varint,1,opt,name=event,proto3,enum=cluster.services.api.ClusterEvent" json:"event,omitempty"`
	WrappedMessage *anypb.Any             `protobuf:"bytes,2,opt,name=wrappedMessage,proto3" json:"wrappedMessage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterMessage) Reset() {
	*x = ClusterMessage{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage) ProtoMessage() {}

func (x *ClusterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage.ProtoReflect.Descriptor instead.
func (*ClusterMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterMessage) GetEvent() ClusterEvent {
	if x != nil {
		return x.Event
	}
	return ClusterEvent_ERROR
}

func (x *ClusterMessage) GetWrappedMessage() *anypb.Any {
	if x != nil {
		return x.WrappedMessage
	}
	return nil
}

// IBRL: Beacon module messages
type BeaconMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BeaconNodeId     string                 `protobuf:"bytes,1,opt,name=beacon_node_id,json=beaconNodeId,proto3" json:"beacon_node_id,omitempty"`
	NodeSignature    []byte                 `protobuf:"bytes,2,opt,name=node_signature,json=nodeSignature,proto3" json:"node_signature,omitempty"`
	Timestamp        int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReputationScore  string                 `protobuf:"bytes,4,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`
	NodeCapabilities []string               `protobuf:"bytes,5,rep,name=node_capabilities,json=nodeCapabilities,proto3" json:"node_capabilities,omitempty"`
	LatencyMs        float64                `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	JitterMs         float64                `protobuf:"fixed64,7,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	PacketLoss       float64                `protobuf:"fixed64,8,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	QueueDepth       uint32                 `protobuf:"varint,9,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	PricePerGb       float64                `protobuf:"fixed64,10,opt,name=price_per_gb,json=pricePerGb,proto3" json:"price_per_gb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BeaconMetadata) Reset() {
	*x = BeaconMetadata{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconMetadata) ProtoMessage() {}

func (x *BeaconMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconMetadata.ProtoReflect.Descriptor instead.
func (*BeaconMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *BeaconMetadata) GetBeaconNodeId() string {
	if x != nil {
		return x.BeaconNodeId
	}
	return ""
}

func (x *BeaconMetadata) GetNodeSignature() []byte {
	if x != nil {
		return x.NodeSignature
	}
	return nil
}

func (x *BeaconMetadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BeaconMetadata) GetReputationScore() string {
	if x != nil {
		return x.ReputationScore
	}
	return ""
}

func (x *BeaconMetadata) GetNodeCapabilities() []string {
	if x != nil {
		return x.NodeCapabilities
	}
	return nil
}

func (x *BeaconMetadata) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *BeaconMetadata) GetJitterMs() float64 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *BeaconMetadata) GetPacketLoss() float64 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *BeaconMetadata) GetQueueDepth() uint32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *BeaconMetadata) GetPricePerGb() float64 {
	if x != nil {
		return x.PricePerGb
	}
	return 0
}

type BeaconAttestation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AttestationType string                 `protobuf:"bytes,2,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	AttestationData []byte                 `protobuf:"bytes,3,opt,name=attestation_data,json=attestationData,proto3" json:"attestation_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BeaconAttestation) Reset() {
	*x = BeaconAttestation{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconAttestation) ProtoMessage() {}

func (x *BeaconAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconAttestation.ProtoReflect.Descriptor instead.
func (*BeaconAttestation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *BeaconAttestation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BeaconAttestation) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *BeaconAttestation) GetAttestationData() []byte {
	if x != nil {
		return x.AttestationData
	}
	return nil
}

// IBRL: Policy module messages
type PolicyContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PolicyId         string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Tags             []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	EnforcementLevel string                 `protobuf:"bytes,3,opt,name=enforcement_level,json=enforcementLevel,proto3" json:"enforcement_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PolicyContext) Reset() {
	*x = PolicyContext{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyContext) ProtoMessage() {}

func (x *PolicyContext) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyContext.ProtoReflect.Descriptor instead.
func (*PolicyContext) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyContext) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyContext) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PolicyContext) GetEnforcementLevel() string {
	if x != nil {
		return x.EnforcementLevel
	}
	return ""
}

type PolicyQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	PolicyType    string                 `protobuf:"bytes,2,opt,name=policy_type,json=policyType,proto3" json:"policy_type,omitempty"`
	Context       map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyQuery) Reset() {
	*x = PolicyQuery{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyQuery) ProtoMessage() {}

func (x *PolicyQuery) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyQuery.ProtoReflect.Descriptor instead.
func (*PolicyQuery) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyQuery) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *PolicyQuery) GetPolicyType() string {
	if x != nil {
		return x.PolicyType
	}
	return ""
}

func (x *PolicyQuery) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// IBRL: Proof module messages
type WorkloadProof struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProofHash      string                 `protobuf:"bytes,1,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`
	ProofSignature []byte                 `protobuf:"bytes,2,opt,name=proof_signature,json=proofSignature,proto3" json:"proof_signature,omitempty"`
	Metrics        map[string]string      `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ProofTimestamp int64                  `protobuf:"varint,4,opt,name=proof_timestamp,json=proofTimestamp,proto3" json:"proof_timestamp,omitempty"`
	HypervisorType string                 `protobuf:"bytes,5,opt,name=hypervisor_type,json=hypervisorType,proto3" json:"hypervisor_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkloadProof) Reset() {
	*x = WorkloadProof{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadProof) ProtoMessage() {}

func (x *WorkloadProof) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadProof.ProtoReflect.Descriptor instead.
func (*WorkloadProof) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *WorkloadProof) GetProofHash() string {
	if x != nil {
		return x.ProofHash
	}
	return ""
}

func (x *WorkloadProof) GetProofSignature() []byte {
	if x != nil {
		return x.ProofSignature
	}
	return nil
}

func (x *WorkloadProof) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *WorkloadProof) GetProofTimestamp() int64 {
	if x != nil {
		return x.ProofTimestamp
	}
	return 0
}

func (x *WorkloadProof) GetHypervisorType() string {
	if x != nil {
		return x.HypervisorType
	}
	return ""
}

type ProofVerification struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId         string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	ProofHash          string                 `protobuf:"bytes,2,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`
	VerificationResult string                 `protobuf:"bytes,3,opt,name=verification_result,json=verificationResult,proto3" json:"verification_result,omitempty"`
	BeaconRegistryHash string                 `protobuf:"bytes,4,opt,name=beacon_registry_hash,json=beaconRegistryHash,proto3" json:"beacon_registry_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProofVerification) Reset() {
	*x = ProofVerification{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofVerification) ProtoMessage() {}

func (x *ProofVerification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofVerification.ProtoReflect.Descriptor instead.
func (*ProofVerification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ProofVerification) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *ProofVerification) GetProofHash() string {
	if x != nil {
		return x.ProofHash
	}
	return ""
}

func (x *ProofVerification) GetVerificationResult() string {
	if x != nil {
		return x.VerificationResult
	}
	return ""
}

func (x *ProofVerification) GetBeaconRegistryHash() string {
	if x != nil {
		return x.BeaconRegistryHash
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type VmSpawnRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Cores    uint32                 `protobuf:"varint,1,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory   uint32                 `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	ImageRef string                 `protobuf:"bytes,3,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	// host port -> container port
	Ports         map[uint32]uint32 `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DryRun        bool              `protobuf:"varint,5,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Env           []string          `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmSpawnRequest) Reset() {
	*x = VmSpawnRequest{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmSpawnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmSpawnRequest) ProtoMessage() {}

func (x *VmSpawnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmSpawnRequest.ProtoReflect.Descriptor instead.
func (*VmSpawnRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *VmSpawnRequest) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *VmSpawnRequest) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *VmSpawnRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *VmSpawnRequest) GetPorts() map[uint32]uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *VmSpawnRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *VmSpawnRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type VmStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmStopRequest) Reset() {
	*x = VmStopRequest{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmStopRequest) ProtoMessage() {}

func (x *VmStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmStopRequest.ProtoReflect.Descriptor instead.
func (*VmStopRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *VmStopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkloadState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceRequest *VmSpawnRequest        `protobuf:"bytes,2,opt,name=source_request,json=sourceRequest,proto3" json:"source_request,omitempty"`
	Proof         *WorkloadProof         `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadState) Reset() {
	*x = WorkloadState{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadState) ProtoMessage() {}

func (x *WorkloadState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadState.ProtoReflect.Descriptor instead.
func (*WorkloadState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *WorkloadState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkloadState) GetSourceRequest() *VmSpawnRequest {
	if x != nil {
		return x.SourceRequest
	}
	return nil
}

func (x *WorkloadState) GetProof() *WorkloadProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

type NodeStateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Node           *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Workloads      []*WorkloadState       `protobuf:"bytes,2,rep,name=workloads,proto3" json:"workloads,omitempty"`
	Beacon         *BeaconMetadata        `protobuf:"bytes,3,opt,name=beacon,proto3" json:"beacon,omitempty"`
	Policy         *PolicyContext         `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	StateSignature string                 `protobuf:"bytes,5,opt,name=state_signature,json=stateSignature,proto3" json:"state_signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeStateResponse) Reset() {
	*x = NodeStateResponse{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStateResponse) ProtoMessage() {}

func (x *NodeStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStateResponse.ProtoReflect.Descriptor instead.
func (*NodeStateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *NodeStateResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeStateResponse) GetWorkloads() []*WorkloadState {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *NodeStateResponse) GetBeacon() *BeaconMetadata {
	if x != nil {
		return x.Beacon
	}
	return nil
}

func (x *NodeStateResponse) GetPolicy() *PolicyContext {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *NodeStateResponse) GetStateSignature() string {
	if x != nil {
		return x.StateSignature
	}
	return ""
}

type NodesStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*NodeStateResponse   `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesStateResponse) Reset() {
	*x = NodesStateResponse{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesStateResponse) ProtoMessage() {}

func (x *NodesStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesStateResponse.ProtoReflect.Descriptor instead.
func (*NodesStateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *NodesStateResponse) GetStates() []*NodeStateResponse {
	if x != nil {
		return x.States
	}
	return nil
}

type VmSpawnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmSpawnResponse) Reset() {
	*x = VmSpawnResponse{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmSpawnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmSpawnResponse) ProtoMessage() {}

func (x *VmSpawnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmSpawnResponse.ProtoReflect.Descriptor instead.
func (*VmSpawnResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *VmSpawnResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmSpawnResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type VmQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmQueryRequest) Reset() {
	*x = VmQueryRequest{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmQueryRequest) ProtoMessage() {}

func (x *VmQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmQueryRequest.ProtoReflect.Descriptor instead.
func (*VmQueryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{15}
}

type VmQueryResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Vms           map[string]*VmSpawnRequest `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmQueryResponse) Reset() {
	*x = VmQueryResponse{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmQueryResponse) ProtoMessage() {}

func (x *VmQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmQueryResponse.ProtoReflect.Descriptor instead.
func (*VmQueryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *VmQueryResponse) GetVms() map[string]*VmSpawnRequest {
	if x != nil {
		return x.Vms
	}
	return nil
}

type VmLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmLogsRequest) Reset() {
	*x = VmLogsRequest{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmLogsRequest) ProtoMessage() {}

func (x *VmLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmLogsRequest.ProtoReflect.Descriptor instead.
func (*VmLogsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *VmLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VmLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmLogsResponse) Reset() {
	*x = VmLogsResponse{}
	mi := &file_pkg_proto_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmLogsResponse) ProtoMessage() {}

func (x *VmLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmLogsResponse.ProtoReflect.Descriptor instead.
func (*VmLogsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *VmLogsResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_pkg_proto_cluster_proto protoreflect.FileDescriptor

const file_pkg_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/cluster.proto\x12\x14cluster.services.api\x1a\x19google/protobuf/any.proto\"\x88\x01\n" +
	"\x0eClusterMessage\x128\n" +
	"\x05event\x18\x01 \x01(\x0e2\".cluster.services.api.ClusterEventR\x05event\x12<\n" +
	"\x0ewrappedMessage\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x0ewrappedMessage\"\xf3\x02\n" +
	"\x0eBeaconMetadata\x12$\n" +
	"\x0ebeacon_node_id\x18\x01 \x01(\tR\fbeaconNodeId\x12%\n" +
	"\x0enode_signature\x18\x02 \x01(\fR\rnodeSignature\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10reputation_score\x18\x04 \x01(\tR\x0freputationScore\x12+\n" +
	"\x11node_capabilities\x18\x05 \x03(\tR\x10nodeCapabilities\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x01R\tlatencyMs\x12\x1b\n" +
	"\tjitter_ms\x18\a \x01(\x01R\bjitterMs\x12\x1f\n" +
	"\vpacket_loss\x18\b \x01(\x01R\n" +
	"packetLoss\x12\x1f\n" +
	"\vqueue_depth\x18\t \x01(\rR\n" +
	"queueDepth\x12 \n" +
	"\fprice_per_gb\x18\n" +
	" \x01(\x01R\n" +
	"pricePerGb\"\x82\x01\n" +
	"\x11BeaconAttestation\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x10attestation_type\x18\x02 \x01(\tR\x0fattestationType\x12)\n" +
	"\x10attestation_data\x18\x03 \x01(\fR\x0fattestationData\"m\n" +
	"\rPolicyContext\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12+\n" +
	"\x11enforcement_level\x18\x03 \x01(\tR\x10enforcementLevel\"\xd5\x01\n" +
	"\vPolicyQuery\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x1f\n" +
	"\vpolicy_type\x18\x02 \x01(\tR\n" +
	"policyType\x12H\n" +
	"\acontext\x18\x03 \x03(\v2..cluster.services.api.PolicyQuery.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x02\n" +
	"\rWorkloadProof\x12\x1d\n" +
	"\n" +
	"proof_hash\x18\x01 \x01(\tR\tproofHash\x12'\n" +
	"\x0fproof_signature\x18\x02 \x01(\fR\x0eproofSignature\x12J\n" +
	"\ametrics\x18\x03 \x03(\v20.cluster.services.api.WorkloadProof.MetricsEntryR\ametrics\x12'\n" +
	"\x0fproof_timestamp\x18\x04 \x01(\x03R\x0eproofTimestamp\x12'\n" +
	"\x0fhypervisor_type\x18\x05 \x01(\tR\x0ehypervisorType\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x11ProofVerification\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x1d\n" +
	"\n" +
	"proof_hash\x18\x02 \x01(\tR\tproofHash\x12/\n" +
	"\x13verification_result\x18\x03 \x01(\tR\x12verificationResult\x120\n" +
	"\x14beacon_registry_hash\x18\x04 \x01(\tR\x12beaconRegistryHash\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"&\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\x87\x02\n" +
	"\x0eVmSpawnRequest\x12\x14\n" +
	"\x05cores\x18\x01 \x01(\rR\x05cores\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\rR\x06memory\x12\x1b\n" +
	"\timage_ref\x18\x03 \x01(\tR\bimageRef\x12E\n" +
	"\x05ports\x18\x04 \x03(\v2/.cluster.services.api.VmSpawnRequest.PortsEntryR\x05ports\x12\x17\n" +
	"\adry_run\x18\x05 \x01(\bR\x06dryRun\x12\x10\n" +
	"\x03env\x18\x06 \x03(\tR\x03env\x1a8\n" +
	"\n" +
	"PortsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\x1f\n" +
	"\rVmStopRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa7\x01\n" +
	"\rWorkloadState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\x0esource_request\x18\x02 \x01(\v2$.cluster.services.api.VmSpawnRequestR\rsourceRequest\x129\n" +
	"\x05proof\x18\x03 \x01(\v2#.cluster.services.api.WorkloadProofR\x05proof\"\xaa\x02\n" +
	"\x11NodeStateResponse\x12.\n" +
	"\x04node\x18\x01 \x01(\v2\x1a.cluster.services.api.NodeR\x04node\x12A\n" +
	"\tworkloads\x18\x02 \x03(\v2#.cluster.services.api.WorkloadStateR\tworkloads\x12<\n" +
	"\x06beacon\x18\x03 \x01(\v2$.cluster.services.api.BeaconMetadataR\x06beacon\x12;\n" +
	"\x06policy\x18\x04 \x01(\v2#.cluster.services.api.PolicyContextR\x06policy\x12'\n" +
	"\x0fstate_signature\x18\x05 \x01(\tR\x0estateSignature\"U\n" +
	"\x12NodesStateResponse\x12?\n" +
	"\x06states\x18\x01 \x03(\v2'.cluster.services.api.NodeStateResponseR\x06states\"3\n" +
	"\x0fVmSpawnResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x10\n" +
	"\x0eVmQueryRequest\"\xb1\x01\n" +
	"\x0fVmQueryResponse\x12@\n" +
	"\x03vms\x18\x01 \x03(\v2..cluster.services.api.VmQueryResponse.VmsEntryR\x03vms\x1a\\\n" +
	"\bVmsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.cluster.services.api.VmSpawnRequestR\x05value:\x028\x01\"\x1f\n" +
	"\rVmLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x0eVmLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs*e\n" +
	"\fClusterEvent\x12\t\n" +
	"\x05ERROR\x10\x00\x12\t\n" +
	"\x05SPAWN\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\x11\n" +
	"\rBEACON_ATTEST\x10\x03\x12\x10\n" +
	"\fPOLICY_QUERY\x10\x04\x12\x10\n" +
	"\fPROOF_VERIFY\x10\x052\xda\x02\n" +
	"\x0eClusterService\x12T\n" +
	"\x05Spawn\x12$.cluster.services.api.VmSpawnRequest\x1a%.cluster.services.api.VmSpawnResponse\x12G\n" +
	"\x04Stop\x12#.cluster.services.api.VmStopRequest\x1a\x1a.cluster.services.api.Node\x12V\n" +
	"\x04List\x12$.cluster.services.api.VmQueryRequest\x1a(.cluster.services.api.NodesStateResponse\x12Q\n" +
	"\x04Logs\x12#.cluster.services.api.VmLogsRequest\x1a$.cluster.services.api.VmLogsResponseB\x1bZ\x19pkg/proto/cluster;clusterb\x06proto3"

var (
	file_pkg_proto_cluster_proto_rawDescOnce sync.Once
	file_pkg_proto_cluster_proto_rawDescData []byte
)

func file_pkg_proto_cluster_proto_rawDescGZIP() []byte {
	file_pkg_proto_cluster_proto_rawDescOnce.Do(func() {
		file_pkg_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_cluster_proto_rawDesc), len(file_pkg_proto_cluster_proto_rawDesc)))
	})
	return file_pkg_proto_cluster_proto_rawDescData
}

var file_pkg_proto_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_proto_cluster_proto_goTypes = []any{
	(ClusterEvent)(0),          // 0: cluster.services.api.ClusterEvent
	(*ClusterMessage)(nil),     // 1: cluster.services.api.ClusterMessage
	(*BeaconMetadata)(nil),     // 2: cluster.services.api.BeaconMetadata
	(*BeaconAttestation)(nil),  // 3: cluster.services.api.BeaconAttestation
	(*PolicyContext)(nil),      // 4: cluster.services.api.PolicyContext
	(*PolicyQuery)(nil),        // 5: cluster.services.api.PolicyQuery
	(*WorkloadProof)(nil),      // 6: cluster.services.api.WorkloadProof
	(*ProofVerification)(nil),  // 7: cluster.services.api.ProofVerification
	(*ErrorResponse)(nil),      // 8: cluster.services.api.ErrorResponse
	(*Node)(nil),               // 9: cluster.services.api.Node
	(*VmSpawnRequest)(nil),     // 10: cluster.services.api.VmSpawnRequest
	(*VmStopRequest)(nil),      // 11: cluster.services.api.VmStopRequest
	(*WorkloadState)(nil),      // 12: cluster.services.api.WorkloadState
	(*NodeStateResponse)(nil),  // 13: cluster.services.api.NodeStateResponse
	(*NodesStateResponse)(nil), // 14: cluster.services.api.NodesStateResponse
	(*VmSpawnResponse)(nil),    // 15: cluster.services.api.VmSpawnResponse
	(*VmQueryRequest)(nil),     // 16: cluster.services.api.VmQueryRequest
	(*VmQueryResponse)(nil),    // 17: cluster.services.api.VmQueryResponse
	(*VmLogsRequest)(nil),      // 18: cluster.services.api.VmLogsRequest
	(*VmLogsResponse)(nil),     // 19: cluster.services.api.VmLogsResponse
	nil,                        // 20: cluster.services.api.PolicyQuery.ContextEntry
	nil,                        // 21: cluster.services.api.WorkloadProof.MetricsEntry
	nil,                        // 22: cluster.services.api.VmSpawnRequest.PortsEntry
	nil,                        // 23: cluster.services.api.VmQueryResponse.VmsEntry
	(*anypb.Any)(nil),          // 24: google.protobuf.Any
}
var file_pkg_proto_cluster_proto_depIdxs = []int32{
	0,  // 0: cluster.services.api.ClusterMessage.event:type_name -> cluster.services.api.ClusterEvent
	24, // 1: cluster.services.api.ClusterMessage.wrappedMessage:type_name -> google.protobuf.Any
	20, // 2: cluster.services.api.PolicyQuery.context:type_name -> cluster.services.api.PolicyQuery.ContextEntry
	21, // 3: cluster.services.api.WorkloadProof.metrics:type_name -> cluster.services.api.WorkloadProof.MetricsEntry
	22, // 4: cluster.services.api.VmSpawnRequest.ports:type_name -> cluster.services.api.VmSpawnRequest.PortsEntry
	10, // 5: cluster.services.api.WorkloadState.source_request:type_name -> cluster.services.api.VmSpawnRequest
	6,  // 6: cluster.services.api.WorkloadState.proof:type_name -> cluster.services.api.WorkloadProof
	9,  // 7: cluster.services.api.NodeStateResponse.node:type_name -> cluster.services.api.Node
	12, // 8: cluster.services.api.NodeStateResponse.workloads:type_name -> cluster.services.api.WorkloadState
	2,  // 9: cluster.services.api.NodeStateResponse.beacon:type_name -> cluster.services.api.BeaconMetadata
	4,  // 10: cluster.services.api.NodeStateResponse.policy:type_name -> cluster.services.api.PolicyContext
	13, // 11: cluster.services.api.NodesStateResponse.states:type_name -> cluster.services.api.NodeStateResponse
	23, // 12: cluster.services.api.VmQueryResponse.vms:type_name -> cluster.services.api.VmQueryResponse.VmsEntry
	10, // 13: cluster.services.api.VmQueryResponse.VmsEntry.value:type_name -> cluster.services.api.VmSpawnRequest
	10, // 14: cluster.services.api.ClusterService.Spawn:input_type -> cluster.services.api.VmSpawnRequest
	11, // 15: cluster.services.api.ClusterService.Stop:input_type -> cluster.services.api.VmStopRequest
	16, // 16: cluster.services.api.ClusterService.List:input_type -> cluster.services.api.VmQueryRequest
	18, // 17: cluster.services.api.ClusterService.Logs:input_type -> cluster.services.api.VmLogsRequest
	15, // 18: cluster.services.api.ClusterService.Spawn:output_type -> cluster.services.api.VmSpawnResponse
	9,  // 19: cluster.services.api.ClusterService.Stop:output_type -> cluster.services.api.Node
	14, // 20: cluster.services.api.ClusterService.List:output_type -> cluster.services.api.NodesStateResponse
	19, // 21: cluster.services.api.ClusterService.Logs:output_type -> cluster.services.api.VmLogsResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pkg_proto_cluster_proto_init() }
func file_pkg_proto_cluster_proto_init() {
	if File_pkg_proto_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_cluster_proto_rawDesc), len(file_pkg_proto_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_cluster_proto_goTypes,
		DependencyIndexes: file_pkg_proto_cluster_proto_depIdxs,
		EnumInfos:         file_pkg_proto_cluster_proto_enumTypes,
		MessageInfos:      file_pkg_proto_cluster_proto_msgTypes,
	}.Build()
	File_pkg_proto_cluster_proto = out.File
	file_pkg_proto_cluster_proto_goTypes = nil
	file_pkg_proto_cluster_proto_depIdxs = nil
}
