package models

import "net"

type TapDetails struct {
	VmIp  net.IP
	TapIp net.IP
	Mask  net.IP
}

// NetworkInterface represents a network interface for the microvm.
type NetworkInterface struct {
	// GuestDeviceName is the name of the network interface to create in the microvm.
	GuestDeviceName string `json:"guest_device_name" validate:"required,excludesall=/@,guestDeviceName"`
	// AllowMetadataRequests indicates that this interface can be used for metadata requests.
	//
	// NOTE: This field is not exposed via the gRPC API, it is automatically
	// populated when converting from the API model to this internal model.
	AllowMetadataRequests bool `json:"allow_mmds,omitempty"`
	// GuestMAC allows the specifying of a specifi MAC address to use for the interface. If
	// not supplied a autogenerated MAC address will be used.
	GuestMAC string `json:"guest_mac,omitempty" validate:"omitempty,mac"`
	// Type is the type of host network interface type to create to use by the guest.
	Type IfaceType `json:"type" validate:"oneof=tap macvtap unsupported"`
	// StaticAddress is an optional static IP address to assign to this interface.
	// If not supplied then DHCP will be used.
	StaticAddress *StaticAddress `json:"staticAddrss,omitempty"`
	// BridgeName is the name of the Linux bridge to attach the TAP device to.
	BridgeName string `json:"branch_name,omitempty"`
}

// StaticAddress specifies a static IP address configuration.
type StaticAddress struct {
	// Address is the static IP address (IPv4 or IPv6) to assign to this interface.
	// Must be CIDR notation.
	Address string `json:"address" validate:"cidr"`
	// Gateway is used to optionally set the default gateway for IPv4 or IPv6.
	Gateway *string `json:"gateway,omitempty" validate:"omitempty,cidr"`
	// Nameservers allows you to optionally specify nameservers for the interface.
	Nameservers []string `json:"nameservers" validate:"omitempty,dive,ip"`
}

type NetworkInterfaceStatus struct {
	// HostDeviceName is the name of the network interface used from the host. This will be
	// a tuntap or macvtap interface.
	HostDeviceName string `json:"host_device_name"`
	// Index is the index of the network interface on the host.
	Index int `json:"index"`
	// MACAddress is the MAC address of the host interface.
	MACAddress string `json:"mac_address"`
	// TAP devicee details
	TapDetails TapDetails
}

// NetworkInterfaceStatuses is a collection of network interfaces.
type NetworkInterfaceStatuses map[string]*NetworkInterfaceStatus

// IfaceType is a type representing the supported network interface types.
type IfaceType string

const (
	// IfaceTypeTap is a TAP network interface.
	IfaceTypeTap IfaceType = "tap"
	// IfaceTypeMacvtap is a MACVTAP network interface.
	IfaceTypeMacvtap IfaceType = "macvtap"
	// IfaceTypeUnsupported is a type that represents an unsupported network interface type.
	IfaceTypeUnsupported IfaceType = "unsupported"
)
