package models

import "net"

type TapDetails struct {
	VMIP  net.IP
	TapIP net.IP
	Mask  net.IP
}

// NetworkInterface represents a network interface for the microvm.
type NetworkInterface struct {
	// GuestMAC allows the specifying of a specifi MAC address to use for the interface. If
	// not supplied a autogenerated MAC address will be used.
	GuestMAC string `json:"guest_mac,omitempty" validate:"omitempty,mac"`
	// BridgeName is the name of the Linux bridge to attach the TAP device to.
	BridgeName string `json:"branch_name,omitempty"`
}

type NetworkInterfaceStatus struct {
	// HostDeviceName is the name of the network interface used from the host. This will be
	// a tuntap or macvtap interface.
	HostDeviceName string `json:"host_device_name"`
	// MACAddress is the MAC address of the host interface.
	MACAddress string `json:"mac_address"`
	// TAP devicee details
	TapDetails TapDetails
}
