name: build
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-actions@v4
        with:
          context: .
          file: "Dockerfile"
          tags: hypercore:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: hypercore:latest
          options: "-v .:/hypercore"
          shell: bash
          run: /hypercore/scripts/package.sh
      - uses: actions/upload-artifact@v4
        with:
          name: hypercore
          path: hypercore.tar.gz
